-- Sample seed inserts. Duplicate and edit prompts to reach 30 per trait/topic.
-- Personality: Extraversion (IPIP-style sample items)
insert into public.assessment_questions (category, sub_category, prompt, options, correct_option_id) values
('personality','Extraversion','I feel comfortable around people.',
	'[{"id":"a1","label":"Strongly disagree"},{"id":"b1","label":"Disagree"},{"id":"c1","label":"Neutral"},{"id":"d1","label":"Agree"},{"id":"e1","label":"Strongly agree"}]', 'd1'),
('personality','Extraversion','I make friends easily.',
	'[{"id":"a2","label":"Strongly disagree"},{"id":"b2","label":"Disagree"},{"id":"c2","label":"Neutral"},{"id":"d2","label":"Agree"},{"id":"e2","label":"Strongly agree"}]', 'd2'),
('personality','Extraversion','I am the life of the party.',
	'[{"id":"a3","label":"Strongly disagree"},{"id":"b3","label":"Disagree"},{"id":"c3","label":"Neutral"},{"id":"d3","label":"Agree"},{"id":"e3","label":"Strongly agree"}]', 'd3'),
('personality','Extraversion','I talk to a lot of different people at parties.',
	'[{"id":"a4","label":"Strongly disagree"},{"id":"b4","label":"Disagree"},{"id":"c4","label":"Neutral"},{"id":"d4","label":"Agree"},{"id":"e4","label":"Strongly agree"}]', 'd4'),
('personality','Extraversion','I don\'t mind being the center of attention.',
	'[{"id":"a5","label":"Strongly disagree"},{"id":"b5","label":"Disagree"},{"id":"c5","label":"Neutral"},{"id":"d5","label":"Agree"},{"id":"e5","label":"Strongly agree"}]', 'd5'),
('personality','Extraversion','I start conversations.',
	'[{"id":"a6","label":"Strongly disagree"},{"id":"b6","label":"Disagree"},{"id":"c6","label":"Neutral"},{"id":"d6","label":"Agree"},{"id":"e6","label":"Strongly agree"}]', 'd6');

-- Skills: Communication (sample items)
insert into public.assessment_questions (category, sub_category, prompt, options, correct_option_id) values
('skills','Communication','I tailor my message to the audience effectively.',
	'[{"id":"a1","label":"Strongly disagree"},{"id":"b1","label":"Disagree"},{"id":"c1","label":"Neutral"},{"id":"d1","label":"Agree"},{"id":"e1","label":"Strongly agree"}]', 'd1'),
('skills','Communication','I actively listen and confirm understanding before responding.',
	'[{"id":"a2","label":"Strongly disagree"},{"id":"b2","label":"Disagree"},{"id":"c2","label":"Neutral"},{"id":"d2","label":"Agree"},{"id":"e2","label":"Strongly agree"}]', 'd2'),
('skills','Communication','My written communication is concise and clear.',
	'[{"id":"a3","label":"Strongly disagree"},{"id":"b3","label":"Disagree"},{"id":"c3","label":"Neutral"},{"id":"d3","label":"Agree"},{"id":"e3","label":"Strongly agree"}]', 'd3'),
('skills','Communication','I ask clarifying questions to avoid misunderstandings.',
	'[{"id":"a4","label":"Strongly disagree"},{"id":"b4","label":"Disagree"},{"id":"c4","label":"Neutral"},{"id":"d4","label":"Agree"},{"id":"e4","label":"Strongly agree"}]', 'd4'),
('skills','Communication','I summarize key points at the end of discussions.',
	'[{"id":"a5","label":"Strongly disagree"},{"id":"b5","label":"Disagree"},{"id":"c5","label":"Neutral"},{"id":"d5","label":"Agree"},{"id":"e5","label":"Strongly agree"}]', 'd5');

-- Repeat patterns for all traits/topics until each has 30 questions.
-- Traits: Extraversion, Agreeableness, Conscientiousness, Neuroticism, Openness
-- Skills: Communication, Teamwork, Reliability, Problem Solving, Organisation and planning, Initiative, Self Management, Leadership, Learning, Technology

-- Real Extraversion (E): 30 Quiz Questions & Answers (High E keyed)
insert into public.assessment_questions (category, sub_category, prompt, options, correct_option_id) values
('personality','Extraversion','How would you typically spend a Friday night?',
	'[{"id":"a1","label":"Stay in alone"},{"id":"b1","label":"Small hangout with a close friend"},{"id":"c1","label":"Go out with a few friends"},{"id":"d1","label":"At a party or large social event."}]','d1'),
('personality','Extraversion','Do you easily speak up and assert your opinions in group settings?',
	'[{"id":"a2","label":"No, I rarely speak up"},{"id":"b2","label":"Only if asked directly"},{"id":"c2","label":"Sometimes, depending on the topic"},{"id":"d2","label":"Yes, I am comfortable asserting my opinions."}]','d2'),
('personality','Extraversion','After spending a day alone, how do you usually feel?',
	'[{"id":"a3","label":"Drained and lonely"},{"id":"b3","label":"Neutral"},{"id":"c3","label":"Rested but fine to stay alone"},{"id":"d3","label":"Rested but quickly eager to interact with others."}]','d3'),
('personality','Extraversion','Do you often find yourself being the person who starts conversations with strangers?',
	'[{"id":"a4","label":"No, almost never"},{"id":"b4","label":"Rarely"},{"id":"c4","label":"Sometimes"},{"id":"d4","label":"Yes, I frequently initiate conversations."}]','d4'),
('personality','Extraversion','Do you prefer a job where you work mostly independently or one that involves constant interaction with clients and colleagues?',
	'[{"id":"a5","label":"Mostly independently"},{"id":"b5","label":"More independent than interactive"},{"id":"c5","label":"Mix of both"},{"id":"d5","label":"One that involves constant interaction."}]','d5'),
('personality','Extraversion','Do you enjoy being the center of attention in a room?',
	'[{"id":"a6","label":"Not at all"},{"id":"b6","label":"Prefer to avoid it"},{"id":"c6","label":"Occasionally"},{"id":"d6","label":"Yes, I often enjoy being the center of attention."}]','d6'),
('personality','Extraversion','When meeting new people, are you reserved or outgoing and affectionate?',
	'[{"id":"a7","label":"Very reserved"},{"id":"b7","label":"Somewhat reserved"},{"id":"c7","label":"Neutral"},{"id":"d7","label":"Outgoing and affectionate (High Warmth)."}]','d7'),
('personality','Extraversion','How quickly do you make new friends?',
	'[{"id":"a8","label":"Very slowly"},{"id":"b8","label":"Slowly"},{"id":"c8","label":"At an average pace"},{"id":"d8","label":"Very quickly and easily."}]','d8'),
('personality','Extraversion','Do you describe yourself as generally cheerful and high-spirited?',
	'[{"id":"a9","label":"No, rarely cheerful"},{"id":"b9","label":"Occasionally cheerful"},{"id":"c9","label":"Often cheerful"},{"id":"d9","label":"Yes, I am generally very cheerful."}]','d9'),
('personality','Extraversion','Do you prefer activities that are calm and quiet, or exciting and fast-paced?',
	'[{"id":"a10","label":"Calm and quiet"},{"id":"b10","label":"Mostly calm"},{"id":"c10","label":"Mix of both"},{"id":"d10","label":"Exciting and fast-paced (Excitement-Seeking)."}]','d10'),
('personality','Extraversion','Are you easily bored when things are quiet or routine?',
	'[{"id":"a11","label":"Not at all"},{"id":"b11","label":"Rarely"},{"id":"c11","label":"Sometimes"},{"id":"d11","label":"Yes, I get bored easily without stimulation."}]','d11'),
('personality','Extraversion','If there is a dispute, are you more likely to mediate or state your own view forcefully?',
	'[{"id":"a12","label":"Avoid or mediate"},{"id":"b12","label":"Gently share a view"},{"id":"c12","label":"Depends on the situation"},{"id":"d12","label":"State my own view forcefully (Assertiveness)."}]','d12'),
('personality','Extraversion','Do you often feel energized and motivated by competition?',
	'[{"id":"a13","label":"Not at all"},{"id":"b13","label":"A little"},{"id":"c13","label":"Sometimes"},{"id":"d13","label":"Yes, I thrive on competition."}]','d13'),
('personality','Extraversion','Do you tend to walk or move quickly, or slowly and deliberately?',
	'[{"id":"a14","label":"Very slowly"},{"id":"b14","label":"Slowly"},{"id":"c14","label":"Average pace"},{"id":"d14","label":"Quickly and energetically (High Activity)."}]','d14'),
('personality','Extraversion','Do you naturally take on leadership roles in temporary groups or social settings?',
	'[{"id":"a15","label":"No"},{"id":"b15","label":"Rarely"},{"id":"c15","label":"Sometimes"},{"id":"d15","label":"Yes, I naturally assume a leadership role."}]','d15'),
('personality','Extraversion','Do you often talk louder than most other people?',
	'[{"id":"a16","label":"No, softer than most"},{"id":"b16","label":"About the same"},{"id":"c16","label":"Slightly louder"},{"id":"d16","label":"Yes, I tend to have a louder voice."}]','d16'),
('personality','Extraversion','Do you prefer a large circle of casual friends or a small circle of close friends?',
	'[{"id":"a17","label":"Small circle of close friends"},{"id":"b17","label":"Mostly small circle"},{"id":"c17","label":"Mix of both"},{"id":"d17","label":"A large circle of casual friends."}]','d17'),
('personality','Extraversion','Do you actively seek out thrilling and risky activities?',
	'[{"id":"a18","label":"No, I avoid risk"},{"id":"b18","label":"Rarely"},{"id":"c18","label":"Sometimes"},{"id":"d18","label":"Yes, I often seek out thrilling activities."}]','d18'),
('personality','Extraversion','How often do you feel joyful and enthusiastic about the future?',
	'[{"id":"a19","label":"Rarely"},{"id":"b19","label":"Occasionally"},{"id":"c19","label":"Often"},{"id":"d19","label":"Very frequently."}]','d19'),
('personality','Extraversion','When going out, do you usually stick with the group you came with, or mingle with others?',
	'[{"id":"a20","label":"Stick with my group"},{"id":"b20","label":"Mostly stick with my group"},{"id":"c20","label":"Mix of both"},{"id":"d20","label":"Mingle with many different people."}]','d20'),
('personality','Extraversion','Do you consider yourself highly persuasive when debating a topic?',
	'[{"id":"a21","label":"Not persuasive"},{"id":"b21","label":"Somewhat persuasive"},{"id":"c21","label":"Often persuasive"},{"id":"d21","label":"Yes, I am generally persuasive."}]','d21'),
('personality','Extraversion','Is your voice expressive, or monotone?',
	'[{"id":"a22","label":"Mostly monotone"},{"id":"b22","label":"Slightly expressive"},{"id":"c22","label":"Moderately expressive"},{"id":"d22","label":"Very expressive."}]','d22'),
('personality','Extraversion','Do you prefer group projects where you can delegate tasks, or solo assignments where you control the outcome?',
	'[{"id":"a23","label":"Solo assignments"},{"id":"b23","label":"Mostly solo"},{"id":"c23","label":"Mix of both"},{"id":"d23","label":"Group projects where I can lead and delegate."}]','d23'),
('personality','Extraversion','Are you generally the first person to volunteer for a public presentation?',
	'[{"id":"a24","label":"No, I avoid presenting"},{"id":"b24","label":"Only if required"},{"id":"c24","label":"Sometimes volunteer"},{"id":"d24","label":"Yes, I am usually the first to volunteer."}]','d24'),
('personality','Extraversion','Do you make plans mostly for yourself, or for large groups of friends?',
	'[{"id":"a25","label":"Mostly for myself"},{"id":"b25","label":"Some for myself"},{"id":"c25","label":"Mix of both"},{"id":"d25","label":"For large groups of friends."}]','d25'),
('personality','Extraversion','Are you talkative, or do you have little to say?',
	'[{"id":"a26","label":"I have little to say"},{"id":"b26","label":"Not very talkative"},{"id":"c26","label":"Moderately talkative"},{"id":"d26","label":"Very talkative."}]','d26'),
('personality','Extraversion','Do you look forward to attending large professional conferences or networking events?',
	'[{"id":"a27","label":"Not at all"},{"id":"b27","label":"A little"},{"id":"c27","label":"Often"},{"id":"d27","label":"Yes, I highly look forward to them."}]','d27'),
('personality','Extraversion','When stressed, do you seek out company or solitude?',
	'[{"id":"a28","label":"Prefer solitude"},{"id":"b28","label":"Mostly solitude"},{"id":"c28","label":"Depends"},{"id":"d28","label":"I seek out the company of others."}]','d28'),
('personality','Extraversion','Do you frequently laugh out loud?',
	'[{"id":"a29","label":"Rarely"},{"id":"b29","label":"Sometimes"},{"id":"c29","label":"Often"},{"id":"d29","label":"Yes, I laugh frequently and loudly."}]','d29'),
('personality','Extraversion','Do you prefer communicating via text/email or phone/in-person conversation?',
	'[{"id":"a30","label":"Text or email"},{"id":"b30","label":"Mostly text/email"},{"id":"c30","label":"Mix of both"},{"id":"d30","label":"Phone or in-person conversation."}]','d30');
