-- Full seed data for all 50 job companies across various sectors
-- Run this in Supabase SQL editor after creating the schema

-- Category: Tech Giants and Cloud Providers
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(1,'Google (Alphabet)','https://careers.google.com/','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','Data Engineering','IoT','VLSI'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/google.com'),
(2,'Microsoft','https://careers.microsoft.com/','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','Data Engineering','IoT'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/microsoft.com'),
(3,'Amazon (AWS)','https://www.amazon.jobs/','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','Data Engineering','IoT','VLSI'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/amazon.com'),
(4,'NVIDIA','https://www.nvidia.com/en-in/about-nvidia/careers/','Tech Giants & Cloud',
	ARRAY['VLSI','Advanced VLSI','AI/ML'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/nvidia.com'),
(5,'IBM','https://www.ibm.com/careers','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','IoT'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/ibm.com'),
(6,'Meta (Facebook)','https://www.metacareers.com/','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','Data Engineering','Data Visualization'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/meta.com'),
(7,'Apple','https://www.apple.com/jobs/','Tech Giants & Cloud',
	ARRAY['AI/ML','Data Science','VLSI'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/apple.com'),
(8,'Cisco','https://jobs.cisco.com/','Tech Giants & Cloud',
	ARRAY['IoT','Data Analytics','Networking AI/ML'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/cisco.com'),
(9,'Intel','https://www.intel.com/content/www/us/en/jobs/careers.html','Tech Giants & Cloud',
	ARRAY['VLSI','Advanced VLSI','AI/ML','IoT'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/intel.com'),
(10,'Oracle','https://www.oracle.com/corporate/careers/','Tech Giants & Cloud',
	ARRAY['Data Science','Data Engineering','Cloud AI/ML'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/oracle.com');

-- Category: VLSI and Semiconductor Specialists
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(11,'Qualcomm','https://careers.qualcomm.com/careers','VLSI & Semiconductors',
	ARRAY['VLSI','Advanced VLSI','On-device AI'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/qualcomm.com'),
(12,'Broadcom','https://www.broadcom.com/company/careers','VLSI & Semiconductors',
	ARRAY['VLSI','Networking','Semiconductor Design'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/broadcom.com'),
(13,'Texas Instruments','https://careers.ti.com/','VLSI & Semiconductors',
	ARRAY['VLSI','Analog/Mixed-Signal','IoT'], ARRAY['ECE','CS'],
	'https://logo.clearbit.com/ti.com'),
(14,'NXP Semiconductors','https://www.nxp.com/company/careers:CAREERS','VLSI & Semiconductors',
	ARRAY['VLSI','IoT','Automotive Electronics'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/nxp.com'),
(15,'Synopsys','https://www.synopsys.com/company/careers.html','VLSI & Semiconductors',
	ARRAY['EDA Tools','VLSI Design','Verification'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/synopsys.com'),
(16,'Cadence Design Systems','https://www.cadence.com/en_US/home/company/careers.html','VLSI & Semiconductors',
	ARRAY['EDA Tools','VLSI Design','Verification'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/cadence.com'),
(17,'Applied Materials','https://www.appliedmaterials.com/en/careers.html','VLSI & Semiconductors',
	ARRAY['Semiconductor Manufacturing','Process'], ARRAY['ECE','BME'],
	'https://logo.clearbit.com/appliedmaterials.com'),
(18,'AMD','https://jobs.amd.com/','VLSI & Semiconductors',
	ARRAY['VLSI','CPU/GPU','Advanced Computing'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/amd.com'),
(19,'ARM','https://www.arm.com/company/careers','VLSI & Semiconductors',
	ARRAY['VLSI','CPU Architecture','Embedded Systems'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/arm.com');

-- Category: Consulting and IT Services Giants
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(20,'TCS','https://www.tcs.com/careers','Consulting & IT Services',
	ARRAY['Data Science','AI/ML','Data Engineering','Data Visualization','IoT'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/tcs.com'),
(21,'Infosys','https://www.infosys.com/careers.html','Consulting & IT Services',
	ARRAY['Data Science','AI/ML','Data Engineering','Data Visualization'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/infosys.com'),
(22,'Wipro','https://careers.wipro.com/','Consulting & IT Services',
	ARRAY['Data Science','AI/ML','Data Engineering','IoT','VLSI'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/wipro.com'),
(23,'Accenture','https://www.accenture.com/in-en/careers','Consulting & IT Services',
	ARRAY['AI & Data Science','Data Engineering','Data Visualization','IoT'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/accenture.com'),
(24,'Capgemini','https://www.capgemini.com/careers/','Consulting & IT Services',
	ARRAY['Data & AI','Data Visualization','Data Engineering'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/capgemini.com'),
(25,'Deloitte','https://www2.deloitte.com/global/en/careers.html','Consulting & IT Services',
	ARRAY['Data Analytics','AI/ML Consulting','Data Visualization'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/deloitte.com'),
(26,'PwC','https://www.pwc.in/careers.html','Consulting & IT Services',
	ARRAY['Data Analytics','AI/ML Consulting','Data Visualization'], ARRAY['CS','IT','ECE','BME'],
	'https://logo.clearbit.com/pwc.com'),
(27,'HCLTech','https://www.hcltech.com/careers','Consulting & IT Services',
	ARRAY['AI/ML','Data Engineering','VLSI Services','IoT'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/hcltech.com'),
(28,'Tech Mahindra','https://www.techmahindra.com/en-in/careers/','Consulting & IT Services',
	ARRAY['AI/ML','Data Analytics','IoT','Telecom'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/techmahindra.com'),
(29,'L&T Technology Services','https://www.ltts.com/careers','Consulting & IT Services',
	ARRAY['AI/ML','IoT','Embedded Systems','Data Analytics'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/ltts.com');

-- Category: Biotech/Healthcare and Automotive/Industrial
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(30,'Siemens Healthineers','https://jobs.siemens-healthineers.com/','Healthcare & Industrial',
	ARRAY['AI/ML','Medical Imaging','Data Analytics'], ARRAY['BME','ECE','CS'],
	'https://logo.clearbit.com/siemens-healthineers.com'),
(31,'Medtronic','https://jobs.medtronic.com/','Healthcare & Industrial',
	ARRAY['AI/ML','IoT','Medical Devices','Data Analytics'], ARRAY['BME','ECE','CS'],
	'https://logo.clearbit.com/medtronic.com'),
(32,'Johnson & Johnson','https://jobs.jnj.com/','Healthcare & Industrial',
	ARRAY['Data Science','AI/ML'], ARRAY['BME','CS','IT'],
	'https://logo.clearbit.com/jnj.com'),
(33,'Bosch','https://www.bosch-career.in/','Healthcare & Industrial',
	ARRAY['AI/ML','IoT','Embedded'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/bosch.com'),
(34,'Continental','https://www.continental-jobs.com/','Healthcare & Industrial',
	ARRAY['AI/ML','Autonomous Driving','Embedded','IoT'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/continental.com'),
(35,'General Electric (GE)','https://www.ge.com/careers','Healthcare & Industrial',
	ARRAY['Industrial IoT','Data Analytics','AI/ML'], ARRAY['ECE','IT','CS','BME'],
	'https://logo.clearbit.com/ge.com'),
(36,'Honeywell','https://careers.honeywell.com/','Healthcare & Industrial',
	ARRAY['Industrial IoT','Data Analytics','Embedded'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/honeywell.com');

-- Category: Finance, Fintech, and Data Platforms
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(37,'Goldman Sachs','https://www.goldmansachs.com/careers/','Finance & Data Platforms',
	ARRAY['Data Science','Data Engineering','AI/ML'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/goldmansachs.com'),
(38,'JPMorgan Chase','https://careers.jpmorgan.com/global/en/home','Finance & Data Platforms',
	ARRAY['Data Science','AI/ML','Data Engineering','Data Visualization'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/jpmorganchase.com'),
(39,'Morgan Stanley','https://www.morganstanley.com/about-us/careers','Finance & Data Platforms',
	ARRAY['Data Science','AI/ML','Data Engineering'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/morganstanley.com'),
(40,'Snowflake','https://careers.snowflake.com/','Finance & Data Platforms',
	ARRAY['Data Engineering','Data Analytics','Data Visualization','AI/ML'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/snowflake.com'),
(41,'Databricks','https://databricks.com/company/careers','Finance & Data Platforms',
	ARRAY['Data Engineering','ML Engineering','Data Science'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/databricks.com'),
(42,'Tableau (Salesforce)','https://www.salesforce.com/company/careers/','Finance & Data Platforms',
	ARRAY['Data Visualization','Data Analytics'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/salesforce.com');

-- Category: Other High-Growth Tech
insert into public.job_companies (rank, company_name, careers_url, category, key_areas, relevant_backgrounds, image_url) values
(43,'Adobe','https://www.adobe.com/careers.html','High-Growth Tech',
	ARRAY['AI/ML','Data Science','Data Visualization'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/adobe.com'),
(44,'Netflix','https://jobs.netflix.com/','High-Growth Tech',
	ARRAY['Data Science','Data Analytics','ML Engineering'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/netflix.com'),
(45,'Uber','https://www.uber.com/en-IN/careers/','High-Growth Tech',
	ARRAY['AI/ML','Data Science','Data Engineering'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/uber.com'),
(46,'OpenAI','https://openai.com/careers','High-Growth Tech',
	ARRAY['AI/ML'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/openai.com'),
(47,'Samsung R&D','https://www.samsung.com/in/aboutsamsung/careers/','High-Growth Tech',
	ARRAY['AI/ML','IoT','VLSI','Embedded Systems'], ARRAY['ECE','IT','CS'],
	'https://logo.clearbit.com/samsung.com'),
(48,'Sony Research','https://www.sony.com/en/sony-global-hiring/','High-Growth Tech',
	ARRAY['AI/ML','IoT','Data Science','Image Processing'], ARRAY['ECE','CS','IT'],
	'https://logo.clearbit.com/sony.com'),
(49,'Qualtrics','https://www.qualtrics.com/careers/','High-Growth Tech',
	ARRAY['Data Science','Data Engineering','Data Analytics'], ARRAY['CS','IT','Data Analytics'],
	'https://logo.clearbit.com/qualtrics.com'),
(50,'Zeta (Fintech)','https://www.zeta.tech/careers/','High-Growth Tech',
	ARRAY['Data Science','AI/ML','Data Engineering','Data Visualization'], ARRAY['CS','IT','ECE'],
	'https://logo.clearbit.com/zeta.tech');
