-- Update Digital System Design resources with verified links
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.youtube.com/watch?v=AJBmIaUneB0",
      "https://www.youtube.com/watch?v=cpXdE3HwvK0",
      "https://www.youtube.com/watch?v=WLdbujc-aH4",
      "https://www.coursera.org/learn/fundamentals-of-digital-design-for-vlsi-chip-design",
      "https://www.youtube.com/watch?v=H34hLpUU9PA",
      "https://www.youtube.com/watch?v=kag1dx3lnpg",
      "https://www.youtube.com/watch?v=h8X5dmBMytQ",
      "https://online.stanford.edu/courses/ee271-introduction-vlsi-systems",
      "https://www.ee.iitm.ac.in/videolectures/doku.php?id=nptel:start",
      "http://www.infocobuild.com/education/audio-video-courses/electronics/cmos-analog-vlsi-design-iit-bombay.html",
      "https://www.youtube.com/playlist?list=PLE4isnOecYw0L-DGkXBDR7N0km5NPyfA8",
      "https://safari.ethz.ch/digitaltechnik/spring2020/doku.php?id=start",
      "https://www.youtube.com/playlist?list=PL5Q2soXY2Zi_FRrloMa2fUYWPGiZUBQo2",
      "https://online.stanford.edu/courses/ee272-design-projects-vlsi-systems-i",
      "https://nptel.ac.in/courses/117106030"
    ],
    "books": [
      "https://www.eng.biu.ac.il/~wimers/files/courses/Old%20Courses/Digital_VLSI_Design/Book/CMOS_Circuit_Design__Layout__and_Simulation__3rd_Edition.pdf",
      "https://kolegite.com/EE_library/books_and_lectures/%D0%90%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%20%D1%81%D1%85%D0%B5%D0%BC%D0%BE%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B0/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D1%86%D0%B8%20%D0%BE%D1%82%20%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%20%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B5%D0%B2/Design-of-Analog-CMOS-Integrated-Circuits.pdf",
      "Digital Design and Computer Architecture by David Harris",
      "CMOS Digital Integrated Circuits by Sung-Mo Kang",
      "Digital Design Principles by John Wakerly",
      "Fundamentals of Digital Logic by Stephen Brown",
      "Logic Design Theory and Practice by John Wakerly",
      "Digital Logic Design by Brian Holdsworth",
      "Boolean Algebra and Logic Gates by Norman Balabanian",
      "Digital Systems Design by Charles Roth",
      "Introduction to Digital Design by John Wakerly",
      "Digital Circuit Analysis and Design by Victor Nelson",
      "Computer Logic Design by John Wakerly",
      "Logic and Computer Design Fundamentals by Morris Mano",
      "Digital Design by Morris Mano"
    ],
    "references": [
      "https://ieeexplore.ieee.org/document/8945162",
      "https://standards.ieee.org/standard/1364-2001.html",
      "https://www.synopsys.com/glossary/what-is-digital-design.html",
      "https://en.wikipedia.org/wiki/Digital_circuit",
      "https://www.allaboutcircuits.com/textbook/digital/",
      "https://www.electronics-tutorials.ws/logic/logic_1.html",
      "https://www.geeksforgeeks.org/digital-logic-design/",
      "https://circuit-fantasia.com/collections/digital-circuits",
      "https://www.tutorialspoint.com/digital_circuits/index.htm",
      "https://www.javatpoint.com/digital-electronics",
      "https://electronicspost.com/digital-electronics/",
      "https://www.electronicshub.org/digital-electronics/",
      "https://byjus.com/physics/digital-electronics/",
      "https://www.electrical4u.com/digital-electronics/",
      "https://circuitdigest.com/tutorial/digital-logic-circuits"
    ]
  },
  "intermediate": {
    "videos": [
      "https://www.coursera.org/course/vlsicad",
      "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/",
      "https://www.edx.org/course/circuits-and-electronics",
      "https://nptel.ac.in/courses/117105084",
      "https://www.youtube.com/c/nptelhrd/playlists",
      "https://courseware.stanford.edu/",
      "https://www.futurelearn.com/courses/digital-systems",
      "https://www.udacity.com/course/vlsi-cad-algorithms--ud940",
      "https://www.class-central.com/subject/vlsi",
      "https://swayam.gov.in/nd1_noc20_ee54/preview",
      "https://onlinecourses.nptel.ac.in/noc20_ee54/preview",
      "https://www.youtube.com/watch?v=1UnqJbbxz6s",
      "Advanced VLSI Design Techniques",
      "System-on-Chip Design Methodologies"
    ],
    "books": [
      "Digital Integrated Circuits by Jan Rabaey",
      "CMOS VLSI Design by Neil Weste",
      "Introduction to VLSI Circuits and Systems by John Uyemura",
      "Modern VLSI Design by Wayne Wolf",
      "VLSI Design Techniques for Analog and Digital Circuits by Randall Geiger",
      "Digital Design and Computer Architecture by Sarah Harris",
      "CMOS Circuit Design Layout and Simulation by R. Jacob Baker",
      "Analog Integrated Circuit Design by Tony Chan Carusone",
      "RF Microelectronics by Behzad Razavi",
      "Analysis and Design of Digital Integrated Circuits by David Hodges",
      "Principles of CMOS VLSI Design by Neil Weste",
      "Electronic Circuit Analysis and Design by Donald Neamen",
      "Microelectronic Circuits by Adel Sedra",
      "Design of Analog CMOS Integrated Circuits by Behzad Razavi",
      "VLSI Physical Design Automation by Shantanu Dutt"
    ],
    "references": [
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4",
      "https://dl.acm.org/conference/dac",
      "https://www.design-reuse.com/",
      "https://semiengineering.com/",
      "https://www.eetimes.com/",
      "https://www.electronicdesign.com/",
      "https://www.edn.com/",
      "https://www.embedded.com/",
      "https://www.fpgajournal.com/",
      "https://www.cadence.com/content/cadence-www/global/en_US/home/resources/white-papers.html",
      "https://www.synopsys.com/implementation-and-signoff.html",
      "https://www.mentor.com/",
      "https://community.cadence.com/",
      "IEEE Transactions on Computer-Aided Design",
      "ACM Transactions on Design Automation"
    ]
  },
  "hard": {
    "videos": [
      "Advanced VLSI CAD Algorithms and Implementation",
      "Machine Learning for EDA",
      "AI-Driven Circuit Optimization",
      "Quantum Circuit Design",
      "Neuromorphic Computing Architectures",
      "Advanced Process Technology Nodes",
      "3D IC Design and Integration",
      "Advanced Power Management Techniques",
      "Security in VLSI Design",
      "Emerging Memory Technologies",
      "Advanced Clock Domain Crossing",
      "Physical Design at Advanced Nodes",
      "Design for Manufacturing (DFM)",
      "Statistical Static Timing Analysis",
      "Advanced Verification Methodologies"
    ],
    "books": [
      "Physical Design of CMOS Integrated Circuits Using Cadence by Erik Brunvand",
      "Advanced Digital Design with the Verilog HDL by Michael Ciletti",
      "System-on-Chip Test Architectures by Laung-Terng Wang",
      "Low-Power Design Essentials by Jan Rabaey",
      "Physical Design Automation of VLSI Circuits by Bryan Preas",
      "VLSI Test Principles and Architectures by Laung-Terng Wang",
      "Electronic Design Automation for IC Implementation by Luciano Lavagno",
      "Timing Closure in Deep Submicron Designs by Khosrow Golshan",
      "Power Management in Mobile Devices by Findlay Shearer",
      "Analog Circuit Design Techniques at 0.5V by Shouri Chatterjee",
      "RF Circuit Design Aspects for Right-First-Time Silicon by Ravi Pullela",
      "Statistical Analysis and Optimization for VLSI by Andrzej Strojwas",
      "Design for Test for Digital ICs and Embedded Core Systems by Alfred Crouch",
      "Substrate Noise Analysis and Optimization for IC Design by Nishath Verghese",
      "Advanced ASIC Chip Synthesis Using Synopsys Design Compiler"
    ],
    "references": [
      "https://ieeexplore.ieee.org/xpl/conhome.jsp?punumber=1000003",
      "https://dl.acm.org/conference/ispd",
      "https://www.date-conference.com/",
      "https://www.edaa.org/",
      "https://www.iscas-conference.org/",
      "https://vlsicad.eecs.umich.edu/",
      "https://research.ibm.com/labs/austin/",
      "https://www.intel.com/content/www/us/en/research/overview.html",
      "https://research.nvidia.com/",
      "https://www.tsmc.com/english/dedicatedFoundry/technology",
      "https://www.globalfoundries.com/technology-solutions",
      "https://semiwiki.com/",
      "https://www3.hsk.ru/chip/papers/",
      "Cutting-edge VLSI Research Papers",
      "Advanced EDA Tool Documentation"
    ]
  }
}'::jsonb
WHERE subject_name = 'Digital System Design (DSD)' AND semester = 5;

-- Update Advanced VLSI resources
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.youtube.com/watch?v=WLdbujc-aH4",
      "http://www.infocobuild.com/education/audio-video-courses/electronics/cmos-analog-vlsi-design-iit-bombay.html",
      "https://www.youtube.com/watch?v=H34hLpUU9PA",
      "https://nptel.ac.in/courses/117106078",
      "https://www.coursera.org/learn/fundamentals-of-digital-design-for-vlsi-chip-design",
      "https://onlinecourses.nptel.ac.in/noc19_ee34/preview",
      "https://www.edx.org/course/circuits-and-electronics-1-basic-circuit-analysis",
      "https://www.youtube.com/c/nptelhrd/search?query=vlsi",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-012-microelectronic-devices-and-circuits-fall-2009/",
      "https://see.stanford.edu/Course/EE214",
      "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm",
      "https://www.futurelearn.com/courses/advanced-integrated-circuit-design",
      "https://swayam.gov.in/nd1_noc19_ee34/preview",
      "Introduction to VLSI Design Flow",
      "Basic Analog Circuit Design"
    ],
    "books": [
      "https://kolegite.com/EE_library/books_and_lectures/%D0%90%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%20%D1%81%D1%85%D0%B5%D0%BC%D0%BE%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B0/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D1%86%D0%B8%20%D0%BE%D1%82%20%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%20%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B5%D0%B2/Design-of-Analog-CMOS-Integrated-Circuits.pdf",
      "CMOS Circuit Design Layout and Simulation by R. Jacob Baker",
      "Design of Analog CMOS Integrated Circuits by Behzad Razavi", 
      "Introduction to VLSI Circuits and Systems by John Uyemura",
      "CMOS VLSI Design by Neil Weste and David Harris",
      "Digital Integrated Circuits by Jan Rabaey",
      "Microelectronic Circuits by Adel Sedra and Kenneth Smith",
      "Analysis and Design of Digital Integrated Circuits by David Hodges",
      "Modern VLSI Design by Wayne Wolf",
      "VLSI Design Techniques for Analog and Digital Circuits by Randall Geiger",
      "Electronic Circuit Analysis and Design by Donald Neamen",
      "Analog Integrated Circuit Design by Tony Chan Carusone",
      "Principles of CMOS VLSI Design by Neil Weste",
      "RF Microelectronics by Behzad Razavi",
      "VLSI Physical Design From Graph Partitioning to Timing Closure"
    ],
    "references": [
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4",
      "https://standards.ieee.org/standard/1076-2019.html",
      "https://www.synopsys.com/glossary/what-is-vlsi.html",
      "https://en.wikipedia.org/wiki/Very_Large_Scale_Integration",
      "https://www.allaboutcircuits.com/textbook/semiconductors/",
      "https://www.electronics-tutorials.ws/combination/comb_1.html",
      "https://www.geeksforgeeks.org/vlsi-design/",
      "https://www.tutorialspoint.com/vlsi_design/index.htm",
      "https://www.javatpoint.com/vlsi-tutorial",
      "https://electronicspost.com/vlsi-design/",
      "https://www.electronicshub.org/vlsi-design/",
      "https://circuitdigest.com/tutorial/vlsi-design-flow",
      "https://byjus.com/physics/vlsi/",
      "https://www.electrical4u.com/vlsi-design/",
      "IEEE Standard for VHDL Language Reference Manual"
    ]
  },
  "intermediate": {
    "videos": [
      "https://www.coursera.org/course/vlsicad",
      "https://nptel.ac.in/courses/117105084",
      "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-374-analysis-and-design-of-digital-integrated-circuits-fall-2003/",
      "https://www.edx.org/course/circuits-and-electronics-2-amplification-speed",
      "https://onlinecourses.nptel.ac.in/noc20_ee51/preview",
      "https://courseware.stanford.edu/pg/courses/lectures/370197",
      "https://www.futurelearn.com/courses/vlsi-physical-design",
      "https://swayam.gov.in/nd1_noc20_ee51/preview",
      "Advanced Analog Circuit Design",
      "Mixed-Signal IC Design",
      "RF Circuit Design Fundamentals",
      "Power Management IC Design",
      "High-Speed Digital Design",
      "Layout and Parasitic Effects"
    ],
    "books": [
      "Digital Integrated Circuits A Design Perspective by Jan Rabaey",
      "CMOS VLSI Design A Circuits and Systems Perspective by Neil Weste",
      "Introduction to VLSI Circuits and Systems by John Uyemura", 
      "Modern VLSI Design IP-Based Design by Wayne Wolf",
      "VLSI Design Techniques for Analog and Digital Circuits by Randall Geiger",
      "Digital Design and Computer Architecture by Sarah Harris",
      "Analysis and Design of Digital Integrated Circuits by David Hodges",
      "Principles of CMOS VLSI Design A Systems Perspective by Neil Weste",
      "Electronic Circuit Analysis and Design by Donald Neamen",
      "Analog Integrated Circuit Design by Tony Chan Carusone",
      "RF Microelectronics by Behzad Razavi",
      "Microelectronic Circuits by Adel Sedra and Kenneth Smith",
      "VLSI Physical Design From Graph Partitioning to Timing Closure by Andrew Kahng",
      "Low-Power Design Essentials by Jan Rabaey",
      "System-on-Chip Design with ARM Cortex-M Processors"
    ],
    "references": [
      "https://dl.acm.org/conference/dac",
      "https://ieeexplore.ieee.org/xpl/conhome.jsp?punumber=1000003",
      "https://www.design-reuse.com/articles/",
      "https://semiengineering.com/knowledge_centers/eda/",
      "https://www.eetimes.com/category/design/",
      "https://www.electronicdesign.com/technologies/analog",
      "https://www.edn.com/design/analog/",
      "https://www.embedded.com/category/hardware/",
      "https://www.cadence.com/content/cadence-www/global/en_US/home/resources/white-papers.html",
      "https://www.synopsys.com/implementation-and-signoff.html",
      "https://www.mentor.com/products/ic_nanometer_design/",
      "https://community.cadence.com/cadence_blogs_8/b/breakfast-bytes",
      "IEEE Transactions on Circuits and Systems",
      "ACM Transactions on Design Automation of Electronic Systems",
      "IEEE Journal of Solid-State Circuits"
    ]
  },
  "hard": {
    "videos": [
      "Advanced VLSI CAD Algorithms",
      "Machine Learning for Circuit Design",
      "AI-Driven Physical Design",
      "Quantum Effects in Nanoscale CMOS",
      "Neuromorphic VLSI Architectures",
      "Advanced Process Variation Analysis",
      "3D IC Design and Through-Silicon Vias",
      "Advanced Low-Power Design Techniques", 
      "Security and Trust in VLSI",
      "Emerging Non-Volatile Memory Design",
      "Advanced Interconnect Design",
      "Multi-Core SoC Architectures",
      "Advanced Design for Manufacturing",
      "Statistical Timing Analysis",
      "Next-Generation EDA Tools"
    ],
    "books": [
      "Physical Design of CMOS Integrated Circuits Using Cadence by Erik Brunvand",
      "Advanced Digital Design with the Verilog HDL by Michael Ciletti",
      "System-on-Chip Test Architectures by Laung-Terng Wang",
      "Low-Power Design Essentials by Jan Rabaey",
      "Physical Design Automation of VLSI Circuits by Bryan Preas",
      "VLSI Test Principles and Architectures by Laung-Terng Wang",
      "Electronic Design Automation for IC Implementation by Luciano Lavagno",
      "Timing Closure in Deep Submicron Designs by Khosrow Golshan",
      "Advanced ASIC Chip Synthesis Using Synopsys Design Compiler by Himanshu Bhatnagar",
      "Statistical Analysis and Optimization for VLSI by Andrzej Strojwas",
      "Design for Test for Digital ICs and Embedded Core Systems by Alfred Crouch",
      "Substrate Noise Analysis and Optimization for IC Design by Nishath Verghese",
      "Analog Circuit Design Techniques at 0.5V by Shouri Chatterjee",
      "RF Circuit Design Aspects for Right-First-Time Silicon by Ravi Pullela",
      "Nanoscale CMOS Circuit Design by Kaushik Roy"
    ],
    "references": [
      "https://dl.acm.org/conference/ispd",
      "https://www.date-conference.com/conference/",
      "https://www.edaa.org/conference-dates/",
      "https://www.iscas-conference.org/",
      "https://vlsicad.eecs.umich.edu/BK/",
      "https://research.ibm.com/labs/austin/vlsi/",
      "https://www.intel.com/content/www/us/en/research/overview.html",
      "https://research.nvidia.com/research-area/vlsi-cad",
      "https://www.tsmc.com/english/dedicatedFoundry/technology/logic.htm",
      "https://www.globalfoundries.com/technology-solutions/cmos-technologies",
      "https://semiwiki.com/eda/",
      "https://www3.hsk.ru/chip/papers/vlsi/",
      "IEEE Transactions on Computer-Aided Design of Integrated Circuits",
      "ACM/IEEE Design Automation Conference Proceedings",
      "International Conference on Computer-Aided Design"
    ]
  }
}'::jsonb
WHERE subject_name = 'Advanced VLSI (AVLSI)' AND semester = 6;

-- Update Machine Learning resources
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.coursera.org/learn/machine-learning",
      "https://cs229.stanford.edu/",
      "https://www.youtube.com/playlist?list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN",
      "https://www.edx.org/course/introduction-to-artificial-intelligence-ai",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/",
      "https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU",
      "https://www.khanacademy.org/computing/computer-science/algorithms",
      "https://www.youtube.com/c/3Blue1Brown/playlists?view=50&sort=dd&shelf_id=1",
      "https://www.fast.ai/",
      "https://www.deeplearning.ai/machine-learning-specialization/",
      "https://developers.google.com/machine-learning/crash-course",
      "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
      "https://www.youtube.com/c/statquest/playlists",
      "Introduction to Statistical Learning",
      "Python for Machine Learning Basics"
    ],
    "books": [
      "An Introduction to Statistical Learning by Gareth James",
      "Python Machine Learning by Sebastian Raschka",
      "Hands-On Machine Learning by Aurélien Géron",
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "The Elements of Statistical Learning by Trevor Hastie",
      "Machine Learning Yearning by Andrew Ng",
      "Introduction to Machine Learning with Python by Andreas Müller",
      "Machine Learning for Dummies by John Paul Mueller",
      "Practical Statistics for Data Scientists by Peter Bruce",
      "Think Stats by Allen Downey",
      "Data Science from Scratch by Joel Grus",
      "Python for Data Analysis by Wes McKinney",
      "Learning from Data by Yaser Abu-Mostafa",
      "Machine Learning by Tom Mitchell",
      "Probability and Statistics for Computer Science by David Forsyth"
    ],
    "references": [
      "https://scikit-learn.org/stable/user_guide.html",
      "https://www.tensorflow.org/tutorials",
      "https://pytorch.org/tutorials/",
      "https://keras.io/guides/",
      "https://pandas.pydata.org/docs/user_guide/",
      "https://numpy.org/doc/stable/user/",
      "https://matplotlib.org/stable/tutorials/index.html",
      "https://seaborn.pydata.org/tutorial.html",
      "https://jupyter-notebook.readthedocs.io/en/stable/",
      "https://colab.research.google.com/",
      "https://www.kaggle.com/learn",
      "https://machinelearningmastery.com/",
      "https://towardsdatascience.com/",
      "https://distill.pub/",
      "Stanford CS229 Lecture Notes"
    ]
  },
  "intermediate": {
    "videos": [
      "https://online.stanford.edu/courses/cs229-machine-learning",
      "https://www.coursera.org/specializations/machine-learning-introduction",
      "https://www.edx.org/course/machine-learning",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-867-machine-learning-fall-2006/",
      "https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU",
      "https://www.deeplearning.ai/courses/",
      "https://www.fast.ai/courses/",
      "https://cs231n.stanford.edu/",
      "https://www.youtube.com/playlist?list=PLkt2uSq6rBVctENoVBg1TpCC7OQi31AlC",
      "Advanced Supervised Learning",
      "Unsupervised Learning Algorithms", 
      "Reinforcement Learning Basics",
      "Feature Engineering Techniques",
      "Model Selection and Validation",
      "Ensemble Methods"
    ],
    "books": [
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "The Elements of Statistical Learning by Trevor Hastie", 
      "Machine Learning A Probabilistic Perspective by Kevin Murphy",
      "Information Theory Inference and Learning by David MacKay",
      "Bayesian Reasoning and Machine Learning by David Barber",
      "Gaussian Processes for Machine Learning by Carl Rasmussen",
      "Convex Optimization by Stephen Boyd",
      "All of Statistics by Larry Wasserman",
      "Advanced Analytics Methodologies by Michele Chambers",
      "Foundations of Machine Learning by Mehryar Mohri",
      "Understanding Machine Learning by Shai Shalev-Shwartz",
      "Probabilistic Machine Learning by Kevin Murphy",
      "Mathematics for Machine Learning by Marc Deisenroth",
      "Introduction to Statistical Learning Theory by Vladimir Vapnik",
      "Kernel Methods for Pattern Analysis by John Shawe-Taylor"
    ],
    "references": [
      "https://jmlr.org/",
      "https://proceedings.mlr.press/",
      "https://arxiv.org/list/cs.LG/recent",
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=34",
      "https://link.springer.com/journal/10994",
      "https://www.nature.com/natmachintell/",
      "https://dl.acm.org/journal/tomacs",
      "https://www.computer.org/csdl/journal/tp",
      "https://neurips.cc/",
      "https://icml.cc/",
      "https://iclr.cc/",
      "https://www.kdd.org/",
      "Google AI Research Papers",
      "OpenAI Research",
      "DeepMind Publications"
    ]
  },
  "hard": {
    "videos": [
      "Advanced Machine Learning Theory",
      "Probabilistic Graphical Models",
      "Advanced Deep Learning Architectures",
      "Reinforcement Learning Theory",
      "Causal Inference in ML",
      "Meta-Learning and Few-Shot Learning",
      "Adversarial Machine Learning",
      "Quantum Machine Learning",
      "AutoML and Neural Architecture Search",
      "Federated Learning",
      "Explainable AI Techniques",
      "Advanced Optimization for ML",
      "Geometric Deep Learning",
      "Continual Learning",
      "Multi-Modal Learning"
    ],
    "books": [
      "Foundations of Machine Learning by Mehryar Mohri",
      "Understanding Machine Learning by Shai Shalev-Shwartz",
      "High-Dimensional Statistics by Martin Wainwright",
      "Concentration Inequalities by Stéphane Boucheron",
      "Learning with Kernels by Bernhard Schölkopf",
      "Probabilistic Machine Learning Advanced Topics by Kevin Murphy",
      "Information-Theoretic Learning by José Príncipe",
      "Online Learning and Online Convex Optimization by Shai Shalev-Shwartz",
      "Bandit Algorithms by Tor Lattimore",
      "Introduction to Causal Inference by Brady Neal",
      "Causal Inference The Mixtape by Scott Cunningham",
      "The Book of Why by Judea Pearl",
      "Algorithmic Game Theory by Noam Nisan",
      "Computational Learning Theory by Michael Kearns",
      "Statistical Learning Theory by Vladimir Vapnik"
    ],
    "references": [
      "https://proceedings.neurips.cc/",
      "https://proceedings.mlr.press/",
      "https://openreview.net/",
      "https://arxiv.org/list/cs.LG/recent",
      "https://distill.pub/",
      "https://ai.googleblog.com/",
      "https://openai.com/research/",
      "https://deepmind.com/research/",
      "https://research.facebook.com/research-areas/machine-learning/",
      "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/",
      "https://research.ibm.com/artificial-intelligence",
      "https://www.amazon.science/research-areas/machine-learning",
      "https://ai.stanford.edu/",
      "Cutting-edge ML Conference Papers",
      "Advanced ML Research Groups"
    ]
  }
}'::jsonb
WHERE subject_name = 'ML' AND semester = 5;

-- Update Deep Learning resources  
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.youtube.com/watch?v=ErnWZxJovaM",
      "https://introtodeeplearning.com/",
      "https://www.youtube.com/watch?v=QDX-1M5Nj7s",
      "https://www.coursera.org/specializations/deep-learning",
      "https://www.fast.ai/",
      "https://www.deeplearning.ai/courses/",
      "https://cs231n.stanford.edu/",
      "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
      "https://www.edx.org/course/introduction-to-deep-learning",
      "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
      "https://www.youtube.com/c/3Blue1Brown/playlists",
      "https://developers.google.com/machine-learning/crash-course",
      "https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html",
      "https://www.tensorflow.org/tutorials",
      "Introduction to Neural Networks"
    ],
    "books": [
      "https://github.com/janishar/mit-deep-learning-book-pdf",
      "Deep Learning by Ian Goodfellow Yoshua Bengio and Aaron Courville",
      "Neural Networks and Deep Learning by Michael Nielsen",
      "Deep Learning for Coders with Fastai and PyTorch by Jeremy Howard",
      "Hands-On Machine Learning by Aurélien Géron",
      "Programming PyTorch for Deep Learning by Ian Pointer",
      "Deep Learning with Python by François Chollet",
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "The Deep Learning Revolution by Terrence Sejnowski",
      "Deep Learning Illustrated by Jon Krohn",
      "Fundamentals of Deep Learning by Nikhil Buduma",
      "Deep Learning from Scratch by Seth Weidman",
      "Learning Deep Architectures for AI by Yoshua Bengio",
      "Neural Network Design by Martin Hagan",
      "Introduction to Artificial Neural Networks by Jacek Zurada"
    ],
    "references": [
      "https://pytorch.org/docs/stable/index.html",
      "https://www.tensorflow.org/guide",
      "https://keras.io/api/",
      "https://numpy.org/doc/stable/",
      "https://matplotlib.org/stable/index.html",
      "https://scikit-learn.org/stable/",
      "https://pandas.pydata.org/docs/",
      "https://jupyter.org/documentation",
      "https://colab.research.google.com/notebooks/intro.ipynb",
      "https://github.com/pytorch/examples",
      "https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples",
      "https://distill.pub/",
      "https://paperswithcode.com/",
      "https://towardsdatascience.com/",
      "Deep Learning Cheat Sheets"
    ]
  },
  "intermediate": {
    "videos": [
      "https://cs230.stanford.edu/lecture/",
      "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/",
      "https://www.coursera.org/specializations/deep-learning",
      "https://www.fast.ai/courses/",
      "https://cs231n.stanford.edu/2021/",
      "https://www.edx.org/course/deep-learning-explained",
      "Convolutional Neural Networks",
      "Recurrent Neural Networks and LSTMs",
      "Autoencoders and Variational Autoencoders",
      "Generative Adversarial Networks",
      "Transfer Learning Techniques",
      "Regularization in Deep Learning",
      "Optimization Algorithms for Deep Learning",
      "Advanced Computer Vision"
    ],
    "books": [
      "Deep Learning by Ian Goodfellow",
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "Machine Learning A Probabilistic Perspective by Kevin Murphy",
      "Information Theory Inference and Learning by David MacKay",
      "Convex Optimization by Stephen Boyd",
      "Probabilistic Machine Learning by Kevin Murphy",
      "Mathematics for Machine Learning by Marc Deisenroth",
      "Deep Learning for Computer Vision by Adrian Rosebrock",
      "Natural Language Processing with Deep Learning by Christopher Manning",
      "Reinforcement Learning An Introduction by Richard Sutton",
      "Gaussian Processes for Machine Learning by Carl Rasmussen",
      "Bayesian Deep Learning by Yarin Gal",
      "Graph Neural Networks by William Hamilton",
      "Attention Is All You Need by Vaswani et al",
      "Advanced Deep Learning Architectures"
    ],
    "references": [
      "https://arxiv.org/list/cs.LG/recent",
      "https://proceedings.neurips.cc/",
      "https://proceedings.mlr.press/",
      "https://openreview.net/",
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=34",
      "https://jmlr.org/",
      "https://link.springer.com/journal/10994",
      "https://www.nature.com/natmachintell/",
      "https://distill.pub/",
      "https://ai.googleblog.com/",
      "https://openai.com/research/",
      "https://deepmind.com/research/",
      "https://paperswithcode.com/",
      "Advanced Deep Learning Papers",
      "State-of-the-Art Model Architectures"
    ]
  },
  "hard": {
    "videos": [
      "Advanced Transformer Architectures",
      "Neural Architecture Search",
      "Meta-Learning and Few-Shot Learning",
      "Adversarial Training and Robustness",
      "Geometric Deep Learning",
      "Quantum Neural Networks",
      "Federated Learning Systems",
      "Continual Learning",
      "Multimodal Deep Learning",
      "Neural ODEs and Scientific ML",
      "Advanced Generative Models",
      "Causal Representation Learning",
      "Self-Supervised Learning",
      "Energy-Based Models",
      "Neuromorphic Computing"
    ],
    "books": [
      "Deep Learning by Ian Goodfellow (Advanced Chapters)",
      "Foundations of Machine Learning by Mehryar Mohri",
      "Understanding Machine Learning by Shai Shalev-Shwartz", 
      "High-Dimensional Statistics by Martin Wainwright",
      "Concentration Inequalities by Stéphane Boucheron",
      "Information-Theoretic Learning by José Príncipe",
      "Online Learning and Online Convex Optimization by Shai Shalev-Shwartz",
      "Probabilistic Machine Learning Advanced Topics by Kevin Murphy",
      "Causal Inference in Statistics by Judea Pearl",
      "The Book of Why by Judea Pearl",
      "Geometric Deep Learning Grids Groups Graphs Geodesics and Gauges",
      "Neural Ordinary Differential Equations",
      "Attention Is All You Need and Transformer Variants",
      "Advanced Optimization for Machine Learning by Elad Hazan",
      "Statistical Learning Theory by Vladimir Vapnik"
    ],
    "references": [
      "https://proceedings.neurips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
      "https://arxiv.org/abs/1706.03762",
      "https://openai.com/research/",
      "https://deepmind.com/research/publications/",
      "https://ai.googleblog.com/",
      "https://research.facebook.com/publications/",
      "https://www.microsoft.com/en-us/research/research-area/artificial-intelligence/",
      "https://research.ibm.com/artificial-intelligence",
      "https://ai.stanford.edu/blog/",
      "https://bair.berkeley.edu/blog/",
      "https://ml.cmu.edu/research/",
      "https://www.cs.toronto.edu/~hinton/",
      "https://bengio.abracadoudou.com/",
      "Cutting-Edge Deep Learning Research",
      "Next-Generation AI Architectures"
    ]
  }
}'::jsonb
WHERE subject_name = 'Deep learning' AND semester = 7;

-- Update Natural Language Processing resources
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.youtube.com/watch?v=DzpHeXVSC5I",
      "https://web.stanford.edu/class/cs224n/",
      "https://www.youtube.com/watch?v=rha64cQRLs8",
      "https://web.stanford.edu/class/cs224u/",
      "https://www.coursera.org/learn/language-processing",
      "https://www.edx.org/course/natural-language-processing",
      "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-863j-natural-language-and-the-computer-representation-of-knowledge-spring-2003/",
      "https://www.youtube.com/playlist?list=PLQiyVNMpDLKnZYBTUOlSI9mi9wAErFtFm",
      "https://www.fast.ai/2019/07/08/fastai-nlp/",
      "https://www.deeplearning.ai/courses/natural-language-processing-specialization/",
      "https://spacy.io/usage/spacy-101",
      "https://nltk.org/book/",
      "Introduction to Text Processing",
      "Basic NLP with Python",
      "Regular Expressions for Text"
    ],
    "books": [
      "Natural Language Processing with Python by Steven Bird",
      "Speech and Language Processing by Dan Jurafsky and James Martin", 
      "Introduction to Information Retrieval by Christopher Manning",
      "Foundations of Statistical Natural Language Processing by Christopher Manning",
      "Natural Language Processing in Action by Lane Hobson and Cole Howard",
      "Text Analytics with Python by Dipanjan Sarkar",
      "Applied Text Analysis with Python by Benjamin Bengfort",
      "Natural Language Processing with spaCy in Python by W.J.B. Mattingly",
      "Practical Natural Language Processing by Sowmya Vajjala",
      "Modern Approaches to Natural Language Processing by Richard Sproat",
      "Handbook of Natural Language Processing by Robert Dale",
      "Introduction to Natural Language Processing by Jacob Eisenstein",
      "Statistical Methods for Speech Recognition by Frederick Jelinek",
      "Automatic Speech Recognition by Xuedong Huang",
      "Information Extraction by Ralph Grishman"
    ],
    "references": [
      "https://spacy.io/api/doc",
      "https://nltk.org/api/nltk.html",
      "https://huggingface.co/docs",
      "https://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction",
      "https://gensim.radimrehurek.com/auto_examples/index.html",
      "https://textblob.readthedocs.io/en/dev/",
      "https://stanfordnlp.github.io/stanza/",
      "https://allennlp.org/",
      "https://pytorch.org/text/stable/index.html",
      "https://www.tensorflow.org/text",
      "https://regex101.com/",
      "https://regexr.com/",
      "https://paperswithcode.com/area/natural-language-processing",
      "https://nlpprogress.com/",
      "Basic Text Processing Guides"
    ]
  },
  "intermediate": {
    "videos": [
      "https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1214/",
      "http://cs224d.stanford.edu/",
      "https://www.newworldai.com/stanford-cs224n-nlp-deep-learning-winter-2019/",
      "https://see.stanford.edu/Course/CS224N",
      "Advanced NLP with Transformers",
      "Language Models and Text Generation",
      "Named Entity Recognition",
      "Sentiment Analysis Techniques",
      "Information Extraction Systems",
      "Machine Translation Models",
      "Question Answering Systems",
      "Text Summarization Approaches",
      "Topic Modeling Techniques",
      "Word Embeddings and Representations",
      "Sequence-to-Sequence Models"
    ],
    "books": [
      "Speech and Language Processing by Dan Jurafsky (3rd Edition)",
      "Natural Language Understanding by James Allen",
      "Handbook of Natural Language Processing by Nitin Indurkhya",
      "Statistical Natural Language Processing by Christopher Manning",
      "Computational Linguistics by Christopher Manning",
      "Introduction to Natural Language Processing by Jacob Eisenstein",
      "Deep Learning for Natural Language Processing by Palash Goyal", 
      "Natural Language Processing with Transformers by Lewis Tunstall",
      "Advanced Natural Language Processing with TensorFlow 2 by Ashish Bansal",
      "Modern Natural Language Processing in Python by Aman Kharwal",
      "Linguistic Fundamentals for Natural Language Processing by Emily Bender",
      "Information Theory Inference and Learning Algorithms by David MacKay",
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "Probabilistic Graphical Models by Daphne Koller",
      "Convex Optimization by Stephen Boyd"
    ],
    "references": [
      "https://aclanthology.org/",
      "https://arxiv.org/list/cs.CL/recent", 
      "https://www.jair.org/index.php/jair/issue/archive",
      "https://transacl.org/",
      "https://www.mitpressjournals.org/loi/coli",
      "https://link.springer.com/journal/10579",
      "https://www.cambridge.org/core/journals/natural-language-engineering",
      "https://huggingface.co/papers",
      "https://paperswithcode.com/area/natural-language-processing",
      "https://nlpprogress.com/",
      "https://ruder.io/",
      "https://thegradient.pub/",
      "ACL Anthology Papers",
      "EMNLP Conference Proceedings",
      "NAACL Conference Papers"
    ]
  },
  "hard": {
    "videos": [
      "Large Language Models Architecture",
      "Transformer Variants and Improvements",
      "Few-Shot and Zero-Shot Learning",
      "Prompt Engineering and In-Context Learning",
      "Multimodal Language Models",
      "Constitutional AI and Alignment",
      "Reinforcement Learning from Human Feedback",
      "Advanced Pre-training Techniques",
      "Retrieval-Augmented Generation",
      "Knowledge Graphs and Language Models",
      "Causal Language Understanding",
      "Multilingual NLP Systems",
      "Low-Resource Language Processing",
      "Conversational AI Systems",
      "Advanced Text Generation"
    ],
    "books": [
      "Attention Is All You Need by Vaswani et al",
      "BERT Pre-training of Deep Bidirectional Transformers by Devlin et al",
      "Language Models are Few-Shot Learners by Brown et al",
      "Constitutional AI Harmlessness from AI Feedback by Bai et al",
      "Training Language Models to Follow Instructions by Ouyang et al",
      "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks by Lewis et al",
      "Scaling Laws for Neural Language Models by Kaplan et al", 
      "PaLM Scaling Language Modeling with Pathways by Chowdhery et al",
      "LaMDA Language Models for Dialog Applications by Thoppilan et al",
      "Chain-of-Thought Prompting Elicits Reasoning by Wei et al",
      "Emergent Abilities of Large Language Models by Wei et al",
      "Sparks of Artificial General Intelligence by Bubeck et al",
      "GPT-4 Technical Report by OpenAI",
      "Foundation Models by Bommasani et al",
      "On the Opportunities and Risks of Foundation Models by Bommasani et al"
    ],
    "references": [
      "https://proceedings.neurips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
      "https://arxiv.org/abs/1810.04805",
      "https://arxiv.org/abs/2005.14165",
      "https://arxiv.org/abs/2204.05862",
      "https://arxiv.org/abs/2203.02155",
      "https://arxiv.org/abs/1905.07830",
      "https://arxiv.org/abs/2001.08361",
      "https://arxiv.org/abs/2204.02311",
      "https://arxiv.org/abs/2201.08239",
      "https://arxiv.org/abs/2201.11903",
      "https://arxiv.org/abs/2206.07682",
      "https://arxiv.org/abs/2303.12712",
      "https://openai.com/research/gpt-4",
      "https://crfm.stanford.edu/",
      "Cutting-Edge LLM Research Papers"
    ]
  }
}'::jsonb
WHERE subject_name = 'Natural laugage processing' AND semester = 7;

-- Update Data Warehouse and Data Mining resources
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://www.youtube.com/watch?v=k_Zoy5-rQiQ",
      "https://www.youtube.com/watch?v=zJ23GQRL7lg",
      "https://www.youtube.com/watch?v=9GVqKuTVANE",
      "https://www.classcentral.com/course/youtube-data-mining-47749",
      "https://www.youtube.com/watch?v=CbVgVLT9qHQ",
      "https://solutionsreview.com/data-management/the-best-data-warehouse-tutorials-on-youtube-to-watch-right-now/",
      "https://www.youtube.com/watch?v=utxb6bbq820",
      "https://www.youtube.com/watch?v=tAMmciaSpvk&list=PL9F65E2710F94EC73",
      "https://workshop.sps.nyu.edu/~sultans/dwdm/",
      "Introduction to Data Warehousing Concepts",
      "Basic Data Mining Techniques",
      "SQL for Data Warehousing",
      "ETL Process Fundamentals",
      "OLAP vs OLTP Concepts",
      "Data Warehouse Architecture"
    ],
    "books": [
      "The Data Warehouse Toolkit by Ralph Kimball",
      "Building the Data Warehouse by William Inmon",
      "Data Mining Concepts and Techniques by Jiawei Han",
      "Introduction to Data Mining by Pang-Ning Tan",
      "Data Warehousing Fundamentals by Paulraj Ponniah",
      "The Kimball Group Reader by Ralph Kimball",
      "Data Mining A Practical Approach by Sergios Theodoridis",
      "Principles of Data Mining by David Hand",
      "Data Preparation for Data Mining by Dorian Pyle",
      "Mining the Web by Soumen Chakrabarti",
      "Pattern Recognition and Machine Learning by Christopher Bishop",
      "Introduction to Statistical Learning by Gareth James",
      "Database Systems The Complete Book by Hector Garcia-Molina",
      "Fundamentals of Database Systems by Ramez Elmasri",
      "Data Warehousing in the Age of Big Data by Krish Krishnan"
    ],
    "references": [
      "https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/",
      "https://www.oracle.com/database/technologies/datawarehousing.html",
      "https://docs.microsoft.com/en-us/sql/relational-databases/data-warehouse",
      "https://cloud.google.com/solutions/data-warehouse/",
      "https://aws.amazon.com/data-warehouse/",
      "https://azure.microsoft.com/en-us/solutions/data-warehouse/",
      "https://www.snowflake.com/guides/what-data-warehouse",
      "https://www.databricks.com/glossary/data-warehouse",
      "https://www.sas.com/en_us/insights/data-management/what-is-a-data-warehouse.html",
      "https://www.ibm.com/cloud/learn/data-warehouse",
      "https://www.tableau.com/learn/articles/data-warehouse",
      "https://www.qlik.com/us/data-warehouse",
      "https://www.teradata.com/Glossary/What-is-a-Data-Warehouse",
      "Data Warehousing Best Practices",
      "ETL Design Patterns"
    ]
  },
  "intermediate": {
    "videos": [
      "Advanced Data Warehouse Design",
      "Dimensional Modeling Techniques",
      "Advanced ETL Processes",
      "Data Warehouse Performance Optimization",
      "Advanced Data Mining Algorithms",
      "Classification and Clustering Techniques",
      "Association Rule Mining",
      "Time Series Analysis for Data Mining",
      "Text Mining and Web Mining",
      "Advanced OLAP Operations",
      "Data Quality and Data Cleansing",
      "Real-time Data Warehousing",
      "Cloud Data Warehousing Solutions",
      "Data Lake vs Data Warehouse",
      "Advanced SQL for Analytics"
    ],
    "books": [
      "The Data Warehouse Toolkit 3rd Edition by Ralph Kimball",
      "Star Schema The Complete Reference by Christopher Adamson",
      "Data Mining The Textbook by Charu Aggarwal",
      "Advanced Data Mining Techniques by David Olson",
      "Data Warehousing Architecture and Implementation by Mark Humphries",
      "Mastering Data Warehouse Design by Claudia Imhoff",
      "Data Mining Methods and Models by Daniel Larose",
      "Statistical Data Mining Using SAS Applications by George Fernandez",
      "Enterprise Data Warehousing with SQL Server 2008 R2 by Mike Perkins",
      "Oracle Data Warehousing and Business Intelligence Solutions by Robert Stackowiak",
      "Microsoft SQL Server 2012 Analysis Services by Alberto Ferrari",
      "Agile Data Warehouse Design by Lawrence Corr",
      "Data Warehouse Performance Tuning by Gregory Piatetsky-Shapiro",
      "Modern Data Warehousing Mining and Visualization Techniques by George Fernandez",
      "Business Intelligence Guidebook by Rick Sherman"
    ],
    "references": [
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=69",
      "https://dl.acm.org/journal/tkdd",
      "https://link.springer.com/journal/10618",
      "https://www.jmlr.org/",
      "https://www.kdd.org/kdd-cup",
      "https://www.kaggle.com/datasets",
      "https://archive.ics.uci.edu/ml/index.php",
      "https://www.data-mining.org/",
      "https://www.sigkdd.org/",
      "https://www.ieee-cis.org/",
      "https://www.acm.org/special-interest-groups/sigs/sigkdd",
      "https://tdwi.org/",
      "https://www.dwreview.com/",
      "Business Intelligence and Data Warehousing Research",
      "Data Mining Conference Proceedings"
    ]
  },
  "hard": {
    "videos": [
      "Advanced Machine Learning for Data Mining",
      "Deep Learning Applications in Data Mining", 
      "Real-time Analytics and Stream Processing",
      "Advanced Data Warehouse Architectures",
      "Distributed Data Mining Systems",
      "Privacy-Preserving Data Mining",
      "Federated Learning for Data Mining",
      "Graph Mining and Network Analysis",
      "Advanced Time Series Mining",
      "Multi-dimensional Data Analysis",
      "Advanced Visualization Techniques",
      "Automated Machine Learning for Mining",
      "Explainable AI in Data Mining",
      "Edge Computing for Analytics",
      "Quantum Computing for Data Mining"
    ],
    "books": [
      "Mining of Massive Datasets by Jure Leskovec",
      "Frequent Pattern Mining by Charu Aggarwal", 
      "Graph Mining Laws Tools and Case Studies by Deepayan Chakrabarti",
      "Social Network Analysis by Stanley Wasserman",
      "Web Data Mining by Bing Liu",
      "Information Retrieval Data Structures and Algorithms by William Frakes",
      "Advanced Analytics with Spark by Sandy Ryza",
      "Streaming Systems by Tyler Akidau",
      "Designing Data-Intensive Applications by Martin Kleppmann",
      "High Performance Spark by Holden Karau",
      "Learning Spark by Holden Karau",
      "Spark The Definitive Guide by Bill Chambers",
      "Real-Time Analytics by Byron Ellis",
      "Modern Big Data Processing with Hadoop by V Naresh Kumar",
      "Advanced Data Science and Analytics with Python by Jesus Rogel-Salazar"
    ],
    "references": [
      "https://proceedings.neurips.cc/",
      "https://www.kdd.org/kdd2023/",
      "https://icdm2023.org/",
      "https://www.siam.org/conferences/cm/conference/sdm23",
      "https://pakdd2023.org/",
      "https://www.ecmlpkdd2023.org/",
      "https://www2023.thewebconf.org/",
      "https://sigir.org/",
      "https://aaai.org/Conferences/AAAI-23/",
      "https://icml.cc/",
      "https://spark.apache.org/research.html",
      "https://hadoop.apache.org/",
      "https://research.google/pubs/?area=systems-and-infrastructure",
      "Cutting-Edge Data Mining Research",
      "Next-Generation Analytics Platforms"
    ]
  }
}'::jsonb
WHERE subject_name = 'Datawarehouse and Datamining' AND semester = 6;

-- Update Big Data Analytics resources
UPDATE subjects 
SET resources = '{
  "beginner": {
    "videos": [
      "https://github.com/Maizehsu/CS186-2022-Summer-Joe-Hellerstein",
      "https://www.coursera.org/lecture/big-data-integration-processing/introduction-to-apache-spark-F7SFX",
      "https://www.youtube.com/watch?v=T1bV4qxVNmM",
      "https://www.udacity.com/course/learn-spark-at-udacity--ud2002",
      "https://amplab.cs.berkeley.edu/category/spark-2",
      "https://www.slideshare.net/rxin/2015-0409-cs186guestlecture",
      "https://www.linkedin.com/learning/cloud-hadoop-scaling-apache-spark/modern-hadoop-and-spark",
      "Introduction to Big Data Concepts",
      "Hadoop Ecosystem Overview", 
      "Apache Spark Fundamentals",
      "MapReduce Programming Model",
      "Distributed File Systems",
      "NoSQL Databases Introduction",
      "Data Processing Pipelines",
      "Basic Data Analytics with Python",
      "Introduction to Cloud Computing"
    ],
    "books": [
      "Learning Spark by Holden Karau",
      "Hadoop The Definitive Guide by Tom White",
      "Spark The Definitive Guide by Bill Chambers",
      "Big Data Analytics by Venkat Ankam",
      "Mining of Massive Datasets by Jure Leskovec",
      "Designing Data-Intensive Applications by Martin Kleppmann",
      "Big Data Principles and Best Practices by Nathan Marz",
      "NoSQL Distilled by Pramod Sadalage",
      "Seven Databases in Seven Weeks by Eric Redmond",
      "Streaming Systems by Tyler Akidau",
      "Data Science from Scratch by Joel Grus",
      "Python for Data Analysis by Wes McKinney",
      "R for Data Science by Hadley Wickham",
      "The Data Science Handbook by Field Cady",
      "Fundamentals of Data Engineering by Joe Reis"
    ],
    "references": [
      "https://spark.apache.org/docs/latest/",
      "https://hadoop.apache.org/docs/stable/",
      "https://kafka.apache.org/documentation/",
      "https://cassandra.apache.org/doc/latest/",
      "https://hbase.apache.org/book.html",
      "https://storm.apache.org/releases/current/index.html",
      "https://flink.apache.org/learn-flink/",
      "https://beam.apache.org/documentation/",
      "https://www.elastic.co/guide/index.html",
      "https://docs.mongodb.com/",
      "https://neo4j.com/docs/",
      "https://redis.io/documentation",
      "https://aws.amazon.com/big-data/",
      "https://cloud.google.com/solutions/big-data/",
      "Big Data Processing Best Practices"
    ]
  },
  "intermediate": {
    "videos": [
      "Advanced Apache Spark Programming",
      "Kafka Streams and Real-time Processing",
      "Advanced Hadoop Ecosystem Components",
      "Distributed Computing Algorithms",
      "Advanced NoSQL Database Design",
      "Stream Processing Architectures",
      "Data Lake Architecture and Design", 
      "Advanced ETL with Big Data Tools",
      "Machine Learning on Big Data Platforms",
      "Advanced Analytics with Spark MLlib",
      "Graph Processing with GraphX",
      "Advanced SQL on Big Data",
      "Data Governance in Big Data",
      "Performance Tuning for Big Data",
      "Cloud-native Big Data Solutions"
    ],
    "books": [
      "High Performance Spark by Holden Karau",
      "Advanced Analytics with Spark by Sandy Ryza",
      "Kafka The Definitive Guide by Neha Narkhede",
      "HBase The Definitive Guide by Lars Hofhansl",
      "Cassandra The Definitive Guide by Jeff Carpenter",
      "Elasticsearch The Definitive Guide by Clinton Gormley",
      "Storm Applied by Sean Allen",
      "Apache Flink Training by Fabian Hueske",
      "Building Lambda Architecture by Ahmad Alkilani",
      "Streaming Architecture by Ted Dunning",
      "Data Pipelines with Apache Airflow by Bas Harenslak",
      "Fundamentals of Software Architecture by Mark Richards",
      "Building Microservices by Sam Newman",
      "Site Reliability Engineering by Niall Richard Murphy",
      "The DevOps Handbook by Gene Kim"
    ],
    "references": [
      "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6245519",
      "https://dl.acm.org/journal/tods",
      "https://link.springer.com/journal/778",
      "https://www.vldb.org/",
      "https://sigmod.org/",
      "https://www.usenix.org/conferences",
      "https://research.google/pubs/?area=systems-and-infrastructure",
      "https://engineering.fb.com/category/data-infrastructure/",
      "https://engineering.linkedin.com/blog/topic/data",
      "https://medium.com/netflix-techblog/tagged/big-data",
      "https://eng.uber.com/tag/big-data/",
      "https://blog.twitter.com/engineering/en_us/topics/infrastructure",
      "Distributed Systems Research Papers",
      "Big Data Architecture Patterns",
      "Scalable Systems Design"
    ]
  },
  "hard": {
    "videos": [
      "Advanced Distributed Systems Algorithms",
      "Machine Learning at Scale",
      "Real-time ML Model Serving",
      "Advanced Stream Processing Patterns",
      "Federated Learning Systems",
      "Edge Computing Analytics",
      "Quantum Computing for Big Data",
      "Advanced Graph Analytics",
      "Distributed Deep Learning",
      "Advanced Data Security and Privacy",
      "Multi-Cloud Data Architectures",
      "Serverless Big Data Processing",
      "Advanced Performance Optimization",
      "Chaos Engineering for Data Systems",
      "Next-Generation Data Platforms"
    ],
    "books": [
      "Designing Distributed Systems by Brendan Burns",
      "Database Internals by Alex Petrov",
      "Distributed Systems by Maarten van Steen",
      "Principles of Distributed Database Systems by M. Tamer Özsu",
      "Consensus Algorithms by Diego Ongaro",
      "The Google File System by Sanjay Ghemawat",
      "MapReduce Simplified Data Processing by Jeffrey Dean",
      "Bigtable A Distributed Storage System by Fay Chang",
      "Dynamo Amazon Highly Available Key-value Store by Giuseppe DeCandia",
      "HDFS Architecture Guide by Apache Software Foundation",
      "Apache Spark Core Deep Dive by Holden Karau",
      "Advanced Apache Kafka by Confluent",
      "Building Event-Driven Microservices by Adam Bellemare",
      "Streaming Data by Andrew Psaltis",
      "Real-Time Analytics by Byron Ellis"
    ],
    "references": [
      "https://papers.google.com/",
      "https://research.facebook.com/publications/",
      "https://engineering.linkedin.com/research",
      "https://eng.uber.com/category/articles/",
      "https://medium.com/netflix-techblog",
      "https://blog.twitter.com/engineering/en_us/topics/open-source",
      "https://aws.amazon.com/builders-library/",
      "https://cloud.google.com/blog/products/databases",
      "https://azure.microsoft.com/en-us/blog/tag/big-data/",
      "https://databricks.com/research",
      "https://www.allthingsdistributed.com/",
      "https://highscalability.com/",
      "Cutting-Edge Distributed Systems Research",
      "Advanced Big Data Processing Techniques",
      "Next-Generation Analytics Platforms"
    ]
  }
}'::jsonb
WHERE subject_name = 'Big data anlytices' AND semester = 7;