// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgtmacrtebcodegjzcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ3RtYWNydGViY29kZWdqemNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjMyMDgsImV4cCI6MjA3MzAzOTIwOH0.ueo75X87MIZKgf0W2_BbXXOa1RO8_wS7Mg-8mcaXii0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});